name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: demo-spring-boot
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build JAR file
        run: mvn package -DskipTests

      - name: Build Docker image
        run: docker build -t ghcr.io/$GITHUB_USERNAME/$IMAGE_NAME:latest .

      - name: Push Docker image to GitHub Packages
        run: |
          echo $DOCKER_PASSWORD | docker login ghcr.io -u $DOCKER_USERNAME --password-stdin
          docker push ghcr.io/$GITHUB_USERNAME/$IMAGE_NAME:latest